// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import (
	_ "embed"

	"fyne.io/fyne/v2"
)

//go:embed images/backgroundcropped.jpg
var resourceBackgroundcroppedJpgData []byte
var resourceBackgroundcroppedJpg = &fyne.StaticResource{
	StaticName:    "images/backgroundcropped.jpg",
	StaticContent: resourceBackgroundcroppedJpgData,
}

//go:embed images/menuBkG.jpg
var resourceMenuBkGJpgData []byte
var resourceMenuBkGJpg = &fyne.StaticResource{
	StaticName:    "images/menuBkG.jpg",
	StaticContent: resourceMenuBkGJpgData,
}

//go:embed images/rally_mapper_logo.png
var resourceRallymapperlogoPngData []byte
var resourceRallymapperlogoPng = &fyne.StaticResource{
	StaticName:    "images/rally_mapper_logo.png",
	StaticContent: resourceRallymapperlogoPngData,
}
